### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by nhnt11** [mozilla/doh-resolver-usage-study#2]
The code needs to be reviewed by a DoH engineer as well as an add-ons peer due to the presence of an experiment API.

**Comment by valenting** [comment]
The main thing I'm worried about is the offline scenario and retries.
How unlikely is it that the user is offline when the addon runs?
In that case we'd get a failure, and quickly retry, record the event with empty IPs, then uninstall it, right?
If we're OK with that, then no action is required.
Otherwise an easy fix I can imagine would be to introduce an X minutes timeout between retries, which will increase the likelyhood that the user will be on a working network when that happens. But if we do that, we would have to do all DNS resolutions as a package deal (ie. we only retry if all of them fail to resolve), otherwise we might find that the user has changed networks in between resolutions 🙂

**Comment by nhnt11** [comment]
@valenting I wanted to avoid worrying about network connectivity for this one. Rationale:

1. These lookups are performed immediately when the add-on is installed. Since the add-on was just fetched from a remote source, it's extremely likely that the internet connection is still alive when the code runs. The retries are mostly to account for server errors.
2. Assuming that the number of clients running into connectivity issues is indeed small, we can just exclude those clients from the analysis - I don't think these outliers have much significance/meaning in this study. 
3. If we see a lot of empty results we can invest in engineering this more. I'd prefer to move quickly on this and do another study if we find that this simple implementation turns out to be problematic after all.

WDYT?

**Comment by valenting** [comment]
If the code is run immediately after fetching the code, I assume that's OK. Thanks for the clarification @nhnt11 
Agreed that we should try to move fast on this. :+1:

**Comment by nhnt11** [comment]
I've replaced the experiment API with an inline UUID implementation in the background script.

**Comment by ddragana** [comment]
Can we put "retryCount" in the unique domain as well, as well as into telemetry?
This is not a strong request, I just think it may be useful for debugging, but do not make this block shipping.

**Comment by mythmon** [comment]
That UUID implementation is kind of amazing and I hope I never have to debug it.

The Normandy bit of this looks fine, and the docs answered most of my questions. :+1:

**Comment by nhnt11** [comment]
> Can we put "retryCount" in the unique domain as well, as well as into telemetry?
> This is not a strong request, I just think it may be useful for debugging, but do not make this block shipping.

Done
